/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorDecorate: typeof import('../components/theme-generator/color-decoration.vue')['default']
    ColorDecoration: typeof import('./../components/theme-generator/color-decoration.vue')['default']
    DirectionToggler: typeof import('./../components/direction-toggler.vue')['default']
    LocaleToggler: typeof import('./../components/locale-toggler.vue')['default']
    PlaygroundGallery: typeof import('./../components/playground-gallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SAffix: typeof import('@soybeanjs/ui')['SAffix']
    SAlert: typeof import('@soybeanjs/ui')['SAlert']
    SBacktop: typeof import('@soybeanjs/ui')['SBacktop']
    SButton: typeof import('@soybeanjs/ui')['SButton']
    SButtonGroup: typeof import('@soybeanjs/ui')['SButtonGroup']
    SCard: typeof import('@soybeanjs/ui')['SCard']
    SColorField: typeof import('@soybeanjs/ui')['SColorField']
    SColorSwatch: typeof import('@soybeanjs/ui')['SColorSwatch']
    SEditable: typeof import('@soybeanjs/ui')['SEditable']
    SIcon: typeof import('@soybeanjs/ui')['SIcon']
    SPopover: typeof import('@soybeanjs/ui')['SPopover']
    SSlider: typeof import('@soybeanjs/ui')['SSlider']
    SSplitterGroup: typeof import('@soybeanjs/ui')['SSplitterGroup']
    SSplitterPanel: typeof import('@soybeanjs/ui')['SSplitterPanel']
    SSplitterResizeHandle: typeof import('@soybeanjs/ui')['SSplitterResizeHandle']
    SSwitch: typeof import('@soybeanjs/ui')['SSwitch']
    SThemeModeSwitch: typeof import('@soybeanjs/ui')['SThemeModeSwitch']
    SToggle: typeof import('@soybeanjs/ui')['SToggle']
    STooltip: typeof import('@soybeanjs/ui')['STooltip']
    SWatermark: typeof import('@soybeanjs/ui')['SWatermark']
    ThemeConfigurator: typeof import('./../components/theme-configurator.vue')['default']
    ThemeGenerator: typeof import('./../components/theme-generator/index.vue')['default']
    ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
  }
}

// For TSX support
declare global {
  const ColorDecorate: typeof import('../components/theme-generator/color-decoration.vue')['default']
  const ColorDecoration: typeof import('./../components/theme-generator/color-decoration.vue')['default']
  const DirectionToggler: typeof import('./../components/direction-toggler.vue')['default']
  const LocaleToggler: typeof import('./../components/locale-toggler.vue')['default']
  const PlaygroundGallery: typeof import('./../components/playground-gallery.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SAffix: typeof import('@soybeanjs/ui')['SAffix']
  const SAlert: typeof import('@soybeanjs/ui')['SAlert']
  const SBacktop: typeof import('@soybeanjs/ui')['SBacktop']
  const SButton: typeof import('@soybeanjs/ui')['SButton']
  const SButtonGroup: typeof import('@soybeanjs/ui')['SButtonGroup']
  const SCard: typeof import('@soybeanjs/ui')['SCard']
  const SColorField: typeof import('@soybeanjs/ui')['SColorField']
  const SColorSwatch: typeof import('@soybeanjs/ui')['SColorSwatch']
  const SEditable: typeof import('@soybeanjs/ui')['SEditable']
  const SIcon: typeof import('@soybeanjs/ui')['SIcon']
  const SPopover: typeof import('@soybeanjs/ui')['SPopover']
  const SSlider: typeof import('@soybeanjs/ui')['SSlider']
  const SSplitterGroup: typeof import('@soybeanjs/ui')['SSplitterGroup']
  const SSplitterPanel: typeof import('@soybeanjs/ui')['SSplitterPanel']
  const SSplitterResizeHandle: typeof import('@soybeanjs/ui')['SSplitterResizeHandle']
  const SSwitch: typeof import('@soybeanjs/ui')['SSwitch']
  const SThemeModeSwitch: typeof import('@soybeanjs/ui')['SThemeModeSwitch']
  const SToggle: typeof import('@soybeanjs/ui')['SToggle']
  const STooltip: typeof import('@soybeanjs/ui')['STooltip']
  const SWatermark: typeof import('@soybeanjs/ui')['SWatermark']
  const ThemeConfigurator: typeof import('./../components/theme-configurator.vue')['default']
  const ThemeGenerator: typeof import('./../components/theme-generator/index.vue')['default']
  const ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
}