export const components = {
  accordion: [
    'AccordionCompact',
    'AccordionRoot',
    'AccordionItem',
    'AccordionHeader',
    'AccordionTrigger',
    'AccordionContent',
    'AccordionDescription'
  ],
  affix: ['AffixCompact', 'AffixRoot', 'AffixPlaceholder', 'AffixContent'],
  alert: ['AlertCompact', 'AlertRoot', 'AlertContent', 'AlertTitle', 'AlertDescription', 'AlertClose'],
  anchor: ['AnchorCompact', 'AnchorItemCompact', 'AnchorLink', 'AnchorRoot'],
  arrow: ['Arrow'],
  aspectRatio: ['AspectRatio'],
  autocomplete: [
    'AutocompleteCompact',
    'AutocompleteRoot',
    'AutocompleteAnchor',
    'AutocompleteInput',
    'AutocompleteTrigger',
    'AutocompletePortal',
    'AutocompleteContent',
    'AutocompleteViewport',
    'AutocompleteGroup',
    'AutocompleteGroupLabel',
    'AutocompleteItem',
    'AutocompleteItemIndicator',
    'AutocompleteSeparator'
  ],
  avatar: ['AvatarRoot', 'AvatarImage', 'AvatarFallback'],
  backtop: ['Backtop'],
  badge: ['BadgeRoot', 'BadgeContent'],
  bottomSheet: [
    'BottomSheetTrigger',
    'BottomSheetPortal',
    'BottomSheetHeader',
    'BottomSheetContent',
    'BottomSheetFooter',
    'BottomSheetTitle',
    'BottomSheetDescription',
    'BottomSheetClose',
    'BottomSheetCancel',
    'BottomSheetConfirm',
    'BottomSheetCompact',
    'BottomSheetRoot',
    'BottomSheetRootNested',
    'BottomSheetPopup',
    'BottomSheetOverlay',
    'BottomSheetHandle'
  ],
  breadcrumb: [
    'BreadcrumbRoot',
    'BreadcrumbCompact',
    'BreadcrumbList',
    'BreadcrumbItem',
    'BreadcrumbLink',
    'BreadcrumbPage',
    'BreadcrumbSeparator',
    'BreadcrumbEllipsis'
  ],
  button: ['Button'],
  calendar: [
    'CalendarCompact',
    'CalendarRoot',
    'CalendarHeader',
    'CalendarHeading',
    'CalendarPrev',
    'CalendarNext',
    'CalendarGrid',
    'CalendarGridHead',
    'CalendarGridBody',
    'CalendarGridRow',
    'CalendarHeadCell',
    'CalendarCell',
    'CalendarCellTrigger'
  ],
  card: [
    'CardRoot',
    'CardHeader',
    'CardTitle',
    'CardTitleRoot',
    'CardDescription',
    'CardContent',
    'CardFooter',
    'CardCollapsibleTrigger',
    'CardCompact'
  ],
  carousel: ['CarouselContent', 'CarouselItem', 'CarouselNext', 'CarouselPrevious', 'CarouselRoot'],
  checkbox: [
    'CheckboxCompact',
    'CheckboxCardCompact',
    'CheckboxGroupCompact',
    'CheckboxCardGroupCompact',
    'CheckboxGroupRoot',
    'CheckboxRoot',
    'CheckboxControl',
    'CheckboxIndicator',
    'CheckboxLabel'
  ],
  clipboard: ['Clipboard'],
  collapsible: ['CollapsibleRoot', 'CollapsibleContent', 'CollapsibleTrigger'],
  colorArea: ['ColorAreaRoot', 'ColorAreaArea', 'ColorAreaThumb'],
  colorField: ['ColorFieldRoot', 'ColorFieldInput'],
  colorPicker: ['ColorPickerRoot'],
  colorSlider: ['ColorSliderRoot', 'ColorSliderTrack', 'ColorSliderThumb'],
  colorSwatch: ['ColorSwatch'],
  colorSwatchPicker: [
    'ColorSwatchPickerRoot',
    'ColorSwatchPickerItem',
    'ColorSwatchPickerItemIndicator',
    'ColorSwatchPickerItemSwatch'
  ],
  combobox: [
    'ComboboxCompact',
    'ComboboxRoot',
    'ComboboxAnchor',
    'ComboboxTrigger',
    'ComboboxPortal',
    'ComboboxViewport',
    'ComboboxContent',
    'ComboboxCancel',
    'ComboboxArrow',
    'ComboboxGroup',
    'ComboboxGroupLabel',
    'ComboboxInput',
    'ComboboxItem',
    'ComboboxItemIndicator',
    'ComboboxEmpty',
    'ComboboxSeparator',
    'ComboboxVirtualizer'
  ],
  command: ['CommandCompact'],
  configProvider: ['ConfigProvider'],
  contextMenu: [
    'ContextMenuRoot',
    'ContextMenuTrigger',
    'ContextMenuPortal',
    'ContextMenuContent',
    'ContextMenuAnchor',
    'ContextMenuArrow',
    'ContextMenuGroup',
    'ContextMenuGroupLabel',
    'ContextMenuItem',
    'ContextMenuItemIndicator',
    'ContextMenuCheckboxItem',
    'ContextMenuRadioItem',
    'ContextMenuSub',
    'ContextMenuSubTrigger',
    'ContextMenuSubContent',
    'ContextMenuSeparator',
    'ContextMenuCheckboxGroup',
    'ContextMenuRadioGroup',
    'ContextMenuCompact',
    'ContextMenuCheckboxCompact',
    'ContextMenuRadioCompact',
    'ContextMenuWrapperCompact'
  ],
  dateField: ['DateFieldCompact', 'DateFieldInput', 'DateFieldRoot'],
  datePicker: ['DatePickerCompact', 'DatePickerContent', 'DatePickerRoot', 'DatePickerTrigger'],
  dateRangeField: ['DateRangeFieldCompact', 'DateRangeFieldInput', 'DateRangeFieldRoot'],
  dateRangePicker: ['DateRangePickerCompact', 'DateRangePickerRoot', 'DateRangePickerTrigger', 'DateRangePickerPopup'],
  dialog: [
    'DialogCompact',
    'DialogProvider',
    'DialogRoot',
    'DialogTrigger',
    'DialogPortal',
    'DialogOverlay',
    'DialogPopup',
    'DialogHeader',
    'DialogContent',
    'DialogTitle',
    'DialogDescription',
    'DialogFooter',
    'DialogClose',
    'DialogCancel',
    'DialogConfirm'
  ],
  dropdownMenu: [
    'DropdownMenuRoot',
    'DropdownMenuTrigger',
    'DropdownMenuPortal',
    'DropdownMenuContent',
    'DropdownMenuAnchor',
    'DropdownMenuArrow',
    'DropdownMenuGroup',
    'DropdownMenuGroupLabel',
    'DropdownMenuItem',
    'DropdownMenuItemIndicator',
    'DropdownMenuCheckboxItem',
    'DropdownMenuRadioItem',
    'DropdownMenuSub',
    'DropdownMenuSubTrigger',
    'DropdownMenuSubContent',
    'DropdownMenuSeparator',
    'DropdownMenuCheckboxGroup',
    'DropdownMenuRadioGroup',
    'DropdownMenuCompact',
    'DropdownMenuCheckboxCompact',
    'DropdownMenuRadioCompact',
    'DropdownMenuWrapperCompact'
  ],
  editable: [
    'EditableArea',
    'EditableCancelTrigger',
    'EditableEditTrigger',
    'EditableInput',
    'EditablePreview',
    'EditableRoot',
    'EditableSubmitTrigger',
    'EditableCompact'
  ],
  empty: ['EmptyRoot', 'EmptyHeader', 'EmptyMedia', 'EmptyContent', 'EmptyTitle', 'EmptyDescription'],
  form: ['FormField', 'FormLabel', 'FormControl', 'FormDescription', 'FormError'],
  hoverCard: [
    'HoverCardRoot',
    'HoverCardTrigger',
    'HoverCardPortal',
    'HoverCardPositioner',
    'HoverCardPopup',
    'HoverCardArrow',
    'HoverCardCompact'
  ],
  input: ['InputRoot', 'InputControl'],
  inputNumber: ['InputNumberRoot', 'InputNumberControl', 'InputNumberIncrement', 'InputNumberDecrement'],
  inputOtp: ['InputOtpCompact', 'InputOtpInput', 'InputOtpPositioner', 'InputOtpRoot'],
  kbd: ['Kbd'],
  label: ['Label'],
  layout: [
    'LayoutCompact',
    'LayoutClassicCompact',
    'LayoutRoot',
    'LayoutSidebar',
    'LayoutRail',
    'LayoutMain',
    'LayoutHeader',
    'LayoutTab',
    'LayoutContent',
    'LayoutFooter',
    'LayoutMobile',
    'LayoutTrigger'
  ],
  link: ['Link'],
  list: ['ListRoot', 'ListItem', 'ListTitle', 'ListDescription', 'ListContent'],
  listbox: [
    'ListboxRoot',
    'ListboxContent',
    'ListboxGroup',
    'ListboxGroupLabel',
    'ListboxItem',
    'ListboxItemIndicator',
    'ListboxFilter',
    'ListboxVirtualizer'
  ],
  menu: [
    'MenuRoot',
    'MenuPortal',
    'MenuContent',
    'MenuAnchor',
    'MenuArrow',
    'MenuGroup',
    'MenuGroupLabel',
    'MenuItem',
    'MenuItemIndicator',
    'MenuCheckboxItem',
    'MenuRadioItem',
    'MenuSub',
    'MenuSubTrigger',
    'MenuSubContent',
    'MenuSeparator',
    'MenuCheckboxGroup',
    'MenuRadioGroup',
    'MenuOptionCompact',
    'MenuOptionsCompact',
    'MenuCheckboxOptionsCompact',
    'MenuRadioOptionsCompact'
  ],
  menubar: [
    'MenubarRoot',
    'MenubarMenu',
    'MenubarTrigger',
    'MenubarPortal',
    'MenubarContent',
    'MenubarArrow',
    'MenubarGroup',
    'MenubarGroupLabel',
    'MenubarItem',
    'MenubarItemIndicator',
    'MenubarCheckboxItem',
    'MenubarRadioItem',
    'MenubarSub',
    'MenubarSubTrigger',
    'MenubarSubContent',
    'MenubarSeparator',
    'MenubarCheckboxGroup',
    'MenubarRadioGroup',
    'MenubarCompact'
  ],
  monthPicker: ['MonthPickerPopup', 'MonthPickerRoot', 'MonthPickerTrigger'],
  monthRangePicker: ['MonthRangePickerPopup', 'MonthRangePickerRoot', 'MonthRangePickerTrigger'],
  navigationMenu: [
    'NavigationMenuRoot',
    'NavigationMenuList',
    'NavigationMenuItem',
    'NavigationMenuTrigger',
    'NavigationMenuContent',
    'NavigationMenuLink',
    'NavigationMenuSubList',
    'NavigationMenuViewport',
    'NavigationMenuIndicator',
    'NavigationMenuCompact'
  ],
  pageTabs: ['PageTabsRoot', 'PageTabsItem', 'PageTabsClose', 'PageTabsPin'],
  pagination: [
    'PaginationRoot',
    'PaginationList',
    'PaginationListItem',
    'PaginationFirst',
    'PaginationPrev',
    'PaginationNext',
    'PaginationLast',
    'PaginationEllipsis',
    'PaginationCompact'
  ],
  popover: [
    'PopoverCompact',
    'PopoverRoot',
    'PopoverTrigger',
    'PopoverAnchor',
    'PopoverPortal',
    'PopoverPositioner',
    'PopoverPopup',
    'PopoverArrow',
    'PopoverClose'
  ],
  popper: ['PopperRoot', 'PopperAnchor', 'PopperPositioner', 'PopperPopup', 'PopperArrow'],
  portal: ['Portal'],
  primitive: ['Primitive'],
  progress: ['ProgressProvider', 'ProgressRoot', 'ProgressIndicator', 'ProgressCircle'],
  radioGroup: [
    'RadioGroupRoot',
    'RadioGroupCompact',
    'RadioGroupItem',
    'RadioGroupControl',
    'RadioGroupIndicator',
    'RadioGroupLabel'
  ],
  rangeCalendar: [
    'RangeCalendarCompact',
    'RangeCalendarRoot',
    'RangeCalendarHeader',
    'RangeCalendarHeading',
    'RangeCalendarPrev',
    'RangeCalendarNext',
    'RangeCalendarGrid',
    'RangeCalendarGridHead',
    'RangeCalendarGridBody',
    'RangeCalendarGridRow',
    'RangeCalendarHeadCell',
    'RangeCalendarCell',
    'RangeCalendarCellTrigger'
  ],
  rovingFocus: ['RovingFocusGroup', 'RovingFocusItem'],
  scrollArea: ['ScrollAreaRoot', 'ScrollAreaViewport', 'ScrollAreaScrollbar', 'ScrollAreaThumb', 'ScrollAreaCorner'],
  segment: ['SegmentRoot', 'SegmentList', 'SegmentTrigger', 'SegmentIndicator', 'SegmentCompact'],
  select: [
    'SelectRoot',
    'SelectCompact',
    'SelectTrigger',
    'SelectPortal',
    'SelectContent',
    'SelectViewport',
    'SelectGroup',
    'SelectGroupLabel',
    'SelectItem',
    'SelectItemIndicator',
    'SelectItemText',
    'SelectValue',
    'SelectTriggerIcon',
    'SelectScrollUpButton',
    'SelectScrollDownButton',
    'SelectSeparator',
    'SelectArrow'
  ],
  separator: ['SeparatorRoot', 'SeparatorLabel'],
  skeleton: ['Skeleton'],
  slider: ['SliderRoot', 'SliderTrack', 'SliderRange', 'SliderThumb'],
  slot: ['Slot'],
  splitter: ['SplitterGroup', 'SplitterPanel', 'SplitterResizeHandle'],
  stepper: [
    'StepperRoot',
    'StepperItem',
    'StepperTrigger',
    'StepperIndicator',
    'StepperSeparator',
    'StepperTitle',
    'StepperDescription',
    'StepperCompact'
  ],
  switch: ['SwitchRoot', 'SwitchControl', 'SwitchThumb'],
  table: [
    'TableCompact',
    'TableRoot',
    'TableScroll',
    'TableContent',
    'TableHeader',
    'TableBody',
    'TableFooter',
    'TableRow',
    'TableHead',
    'TableCell'
  ],
  tabs: ['TabsRoot', 'TabsList', 'TabsTrigger', 'TabsContent', 'TabsIndicator', 'TabsCompact'],
  tag: ['Tag'],
  tagsInput: [
    'TagsInputRoot',
    'TagsInputInput',
    'TagsInputItem',
    'TagsInputItemText',
    'TagsInputItemDelete',
    'TagsInputClear'
  ],
  textarea: ['TextareaRoot', 'TextareaControl', 'TextareaCounter'],
  timeField: ['TimeFieldRoot', 'TimeFieldInput'],
  timePicker: ['TimePickerPopup', 'TimePickerRoot', 'TimePickerTrigger'],
  timeRangeField: ['TimeRangeFieldCompact', 'TimeRangeFieldRoot', 'TimeRangeFieldInput'],
  timeRangePicker: ['TimeRangePickerCompact', 'TimeRangePickerPopup', 'TimeRangePickerRoot', 'TimeRangePickerTrigger'],
  toast: ['Toaster', 'ToastProvider'],
  toggle: ['Toggle'],
  toggleGroup: ['ToggleGroupRoot', 'ToggleGroupItem'],
  toolbar: [
    'ToolbarRoot',
    'ToolbarButton',
    'ToolbarLink',
    'ToolbarSeparator',
    'ToolbarToggleGroup',
    'ToolbarToggleItem'
  ],
  tooltip: ['TooltipRoot', 'TooltipTrigger', 'TooltipPortal', 'TooltipPositioner', 'TooltipPopup', 'TooltipArrow'],
  tree: ['TreeRoot', 'TreeItem', 'TreeVirtualizerRoot', 'TreeVirtualizerItem'],
  treeMenu: [
    'TreeMenuRoot',
    'TreeMenuGroupRoot',
    'TreeMenuGroup',
    'TreeMenuGroupLabel',
    'TreeMenuItem',
    'TreeMenuButton',
    'TreeMenuCollapsible',
    'TreeMenuSub'
  ],
  virtualizer: ['VirtualizerRoot', 'VirtualizerContent', 'VirtualizerItem'],
  visuallyHidden: ['VisuallyHidden', 'VisuallyHiddenInput'],
  yearPicker: ['YearPickerPopup', 'YearPickerRoot', 'YearPickerTrigger'],
  yearRangePicker: ['YearRangePickerPopup', 'YearRangePickerRoot', 'YearRangePickerTrigger']
};
