export const components = {
  accordion: ['AccordionRoot', 'AccordionItem', 'AccordionTrigger', 'AccordionHeader', 'AccordionContent'],
  alert: ['AlertRoot', 'AlertTitle', 'AlertDescription', 'AlertContent', 'AlertClose'],
  alertDialog: [
    'AlertDialogRoot',
    'AlertDialogTrigger',
    'AlertDialogPortal',
    'AlertDialogOverlay',
    'AlertDialogContent',
    'AlertDialogHeader',
    'AlertDialogTitle',
    'AlertDialogDescription',
    'AlertDialogFooter',
    'AlertDialogClose'
  ],
  arrow: ['Arrow'],
  aspectRatio: ['AspectRatio'],
  avatar: ['AvatarRoot', 'AvatarImage', 'AvatarFallback'],
  badge: ['BadgeRoot', 'BadgeContent'],
  breadcrumb: [
    'BreadcrumbRoot',
    'BreadcrumbList',
    'BreadcrumbItem',
    'BreadcrumbLink',
    'BreadcrumbPage',
    'BreadcrumbSeparator',
    'BreadcrumbEllipsis'
  ],
  button: ['Button'],
  card: ['CardRoot', 'CardHeader', 'CardTitle', 'CardTitleRoot', 'CardDescription', 'CardContent', 'CardFooter'],
  checkbox: ['CheckboxGroupRoot', 'CheckboxRoot', 'CheckboxControl', 'CheckboxIndicator', 'CheckboxLabel'],
  collapsible: ['CollapsibleRoot', 'CollapsibleTrigger', 'CollapsibleContent'],
  configProvider: ['ConfigProvider'],
  contextMenu: [
    'ContextMenuRoot',
    'ContextMenuTrigger',
    'ContextMenuPortal',
    'ContextMenuContent',
    'ContextMenuAnchor',
    'ContextMenuArrow',
    'ContextMenuGroup',
    'ContextMenuGroupLabel',
    'ContextMenuItem',
    'ContextMenuItemIndicator',
    'ContextMenuCheckboxItem',
    'ContextMenuRadioItem',
    'ContextMenuSub',
    'ContextMenuSubTrigger',
    'ContextMenuSubContent',
    'ContextMenuSeparator',
    'ContextMenuCheckboxGroup',
    'ContextMenuRadioGroup'
  ],
  dialog: [
    'DialogRoot',
    'DialogTrigger',
    'DialogPortal',
    'DialogOverlay',
    'DialogContent',
    'DialogHeader',
    'DialogTitle',
    'DialogDescription',
    'DialogFooter',
    'DialogClose'
  ],
  dropdownMenu: [
    'DropdownMenuRoot',
    'DropdownMenuTrigger',
    'DropdownMenuPortal',
    'DropdownMenuContent',
    'DropdownMenuAnchor',
    'DropdownMenuArrow',
    'DropdownMenuGroup',
    'DropdownMenuGroupLabel',
    'DropdownMenuItem',
    'DropdownMenuItemIndicator',
    'DropdownMenuCheckboxItem',
    'DropdownMenuRadioItem',
    'DropdownMenuSub',
    'DropdownMenuSubTrigger',
    'DropdownMenuSubContent',
    'DropdownMenuSeparator',
    'DropdownMenuCheckboxGroup',
    'DropdownMenuRadioGroup'
  ],
  form: ['FormField', 'FormLabel', 'FormDescription', 'FormError', 'FormFieldArray'],
  input: ['InputRoot', 'InputControl'],
  inputNumber: ['InputNumberRoot', 'InputNumberControl', 'InputNumberIncrement', 'InputNumberDecrement'],
  kbd: ['Kbd'],
  label: ['Label'],
  layout: [
    'LayoutRoot',
    'LayoutHeader',
    'LayoutMain',
    'LayoutSidebar',
    'LayoutFooter',
    'LayoutRail',
    'LayoutMobile',
    'LayoutTab',
    'LayoutTrigger'
  ],
  link: ['Link'],
  list: ['ListRoot', 'ListItem', 'ListTitle', 'ListDescription', 'ListContent'],
  listbox: [
    'ListboxRoot',
    'ListboxContent',
    'ListboxGroup',
    'ListboxGroupLabel',
    'ListboxItem',
    'ListboxItemIndicator',
    'ListboxFilter',
    'ListboxVirtualizer'
  ],
  menu: [
    'MenuRoot',
    'MenuPortal',
    'MenuContent',
    'MenuAnchor',
    'MenuArrow',
    'MenuGroup',
    'MenuGroupLabel',
    'MenuItem',
    'MenuItemIndicator',
    'MenuCheckboxItem',
    'MenuRadioItem',
    'MenuSub',
    'MenuSubTrigger',
    'MenuSubContent',
    'MenuSeparator',
    'MenuCheckboxGroup',
    'MenuRadioGroup'
  ],
  navigationMenu: [
    'NavigationMenuRoot',
    'NavigationMenuList',
    'NavigationMenuItem',
    'NavigationMenuTrigger',
    'NavigationMenuContent',
    'NavigationMenuLink',
    'NavigationMenuSubList',
    'NavigationMenuViewport',
    'NavigationMenuIndicator'
  ],
  pageTabs: ['PageTabsRoot', 'PageTabsItem', 'PageTabsClose', 'PageTabsPin'],
  pagination: [
    'PaginationRoot',
    'PaginationList',
    'PaginationListItem',
    'PaginationFirst',
    'PaginationPrev',
    'PaginationNext',
    'PaginationLast',
    'PaginationEllipsis'
  ],
  popover: [
    'PopoverRoot',
    'PopoverTrigger',
    'PopoverAnchor',
    'PopoverPortal',
    'PopoverPositioner',
    'PopoverPopup',
    'PopoverArrow',
    'PopoverClose'
  ],
  popper: ['PopperRoot', 'PopperAnchor', 'PopperPopup', 'PopperArrow', 'PopperPositioner'],
  portal: ['Portal'],
  primitive: ['Primitive'],
  radioGroup: ['RadioGroupRoot', 'RadioGroupItem', 'RadioGroupControl', 'RadioGroupIndicator', 'RadioGroupLabel'],
  rovingFocus: ['RovingFocusGroup', 'RovingFocusItem'],
  select: [
    'SelectRoot',
    'SelectTrigger',
    'SelectPortal',
    'SelectContent',
    'SelectViewport',
    'SelectGroup',
    'SelectGroupLabel',
    'SelectItem',
    'SelectItemIndicator',
    'SelectItemText',
    'SelectValue',
    'SelectTriggerIcon',
    'SelectScrollUpButton',
    'SelectScrollDownButton',
    'SelectSeparator',
    'SelectArrow'
  ],
  separator: ['SeparatorRoot', 'SeparatorLabel'],
  slot: ['Slot'],
  switch: ['SwitchRoot', 'SwitchControl', 'SwitchThumb'],
  tabs: ['TabsRoot', 'TabsList', 'TabsTrigger', 'TabsContent', 'TabsIndicator'],
  tag: ['Tag'],
  textarea: ['TextareaRoot', 'TextareaControl', 'TextareaCounter'],
  toast: [
    'ToastProvider',
    'ToastRoot',
    'ToastViewport',
    'ToastPortal',
    'ToastAction',
    'ToastTitle',
    'ToastDescription',
    'ToastClose'
  ],
  tooltip: ['TooltipRoot', 'TooltipTrigger', 'TooltipPortal', 'TooltipPositioner', 'TooltipPopup', 'TooltipArrow'],
  tree: ['TreeRoot', 'TreeItem', 'TreeVirtualizerRoot', 'TreeVirtualizerItem'],
  treeMenu: [
    'TreeMenuRoot',
    'TreeMenuGroupRoot',
    'TreeMenuGroup',
    'TreeMenuGroupLabel',
    'TreeMenuItem',
    'TreeMenuButton',
    'TreeMenuCollapsible',
    'TreeMenuSub'
  ],
  virtualizer: ['VirtualizerRoot', 'VirtualizerContent', 'VirtualizerItem'],
  visuallyHidden: ['VisuallyHidden', 'VisuallyHiddenInput']
};
