packages:
  - 'headless'
  - 'docs'
  - 'nuxt'
  - 'ui-skills'
overrides:
  vite-ssg>jsdom: 27.0.1
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: false
minimumReleaseAge: 0
