import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'ubean';
import UiResolver from '../../packages/ui/src/resolver';
import { collectPrerenderRoutes } from './build/docs-routes';
import { SHIKI_THEMES, createMarkdownHighlight } from './build/highlight';

const rootDir = path.dirname(fileURLToPath(import.meta.url));

const highlightCode = await createMarkdownHighlight();

/**
 * Concrete prerender routes: static shell pages + default-locale content slugs
 * (+ zh-only pages) mapped through the shared route model in `build/docs-routes.ts`.
 * Dynamic param routes are not expanded by `prerender.all`, so content must be
 * listed explicitly; the `/zh` mirrors are generated by the SSG renderer's
 * `expandRoutes` (ubean@0.4.5, prefix_except_default) instead of being listed.
 */
const prerenderRoutes = await collectPrerenderRoutes(rootDir);

export default defineConfig({
  mode: 'ssg',
  favicon: 'https://r2.soybeanjs.tech/soybeanjs/logo-soybean-ui.svg?v=202608192144',
  i18n: {
    defaultLocale: 'en',
    locales: [
      { code: 'en', language: 'en', name: 'English' },
      { code: 'zh', language: 'zh-CN', name: '中文', dir: 'ltr' }
    ],
    strategy: 'prefix_except_default'
  },
  markdown: {
    wrapperClass: 'markdown-body',
    theme: {
      light: SHIKI_THEMES.light,
      dark: SHIKI_THEMES.dark
    },
    markdownExit: {
      highlight: highlightCode
    }
  },
  components: {
    resolvers: [UiResolver()]
  },
  autoImports: {
    vueRouter: true,
    vueI18n: true
  },
  // Theme state is owned by @soybeanjs/theme (createThemeInitScript in app.ts);
  // disabling the built-in colorMode avoids a second, conflicting source.
  colorMode: false,
  prerender: {
    include: prerenderRoutes,
    crawlLinks: true
  },
  security: {
    headers: {
      contentSecurityPolicy: {
        'connect-src': ["'self'", 'ws:', 'wss:', 'https://api.iconify.design']
      }
    }
  }
});
