export const components = {
  accordion: ['AccordionContent', 'AccordionHeader', 'AccordionItem', 'AccordionRoot', 'AccordionTrigger'],
  alert: ['AlertClose', 'AlertContent', 'AlertDescription', 'AlertRoot', 'AlertTitle'],
  alertDialog: [
    'AlertDialogClose',
    'AlertDialogContent',
    'AlertDialogDescription',
    'AlertDialogFooter',
    'AlertDialogHeader',
    'AlertDialogOverlay',
    'AlertDialogPortal',
    'AlertDialogRoot',
    'AlertDialogTitle',
    'AlertDialogTrigger'
  ],
  arrow: ['Arrow'],
  aspectRatio: ['AspectRatio'],
  avatar: ['AvatarFallback', 'AvatarImage', 'AvatarRoot'],
  badge: ['BadgeContent', 'BadgeRoot'],
  breadcrumb: [
    'BreadcrumbEllipsis',
    'BreadcrumbItem',
    'BreadcrumbLink',
    'BreadcrumbList',
    'BreadcrumbPage',
    'BreadcrumbRoot',
    'BreadcrumbSeparator'
  ],
  button: ['Button'],
  card: ['CardContent', 'CardDescription', 'CardFooter', 'CardHeader', 'CardRoot', 'CardTitleRoot', 'CardTitle'],
  checkbox: ['CheckboxControl', 'CheckboxGroupRoot', 'CheckboxIndicator', 'CheckboxLabel', 'CheckboxRoot'],
  collapsible: ['CollapsibleContent', 'CollapsibleRoot', 'CollapsibleTrigger'],
  configProvider: ['ConfigProvider'],
  contextMenu: [
    'ContextMenuAnchor',
    'ContextMenuArrow',
    'ContextMenuCheckboxGroup',
    'ContextMenuCheckboxItem',
    'ContextMenuContent',
    'ContextMenuGroup',
    'ContextMenuGroupLabel',
    'ContextMenuItem',
    'ContextMenuItemIndicator',
    'ContextMenuPortal',
    'ContextMenuRadioGroup',
    'ContextMenuRadioItem',
    'ContextMenuRoot',
    'ContextMenuSeparator',
    'ContextMenuSub',
    'ContextMenuSubContent',
    'ContextMenuSubTrigger',
    'ContextMenuTrigger'
  ],
  dialog: [
    'DialogClose',
    'DialogContent',
    'DialogDescription',
    'DialogFooter',
    'DialogHeader',
    'DialogOverlay',
    'DialogPortal',
    'DialogRoot',
    'DialogTitle',
    'DialogTrigger'
  ],
  divider: ['DividerLabel', 'DividerRoot'],
  dropdownMenu: [
    'DropdownMenuAnchor',
    'DropdownMenuArrow',
    'DropdownMenuCheckboxGroup',
    'DropdownMenuCheckboxItem',
    'DropdownMenuContent',
    'DropdownMenuGroup',
    'DropdownMenuGroupLabel',
    'DropdownMenuItem',
    'DropdownMenuItemIndicator',
    'DropdownMenuPortal',
    'DropdownMenuRadioGroup',
    'DropdownMenuRadioItem',
    'DropdownMenuRoot',
    'DropdownMenuSeparator',
    'DropdownMenuSub',
    'DropdownMenuSubContent',
    'DropdownMenuSubTrigger',
    'DropdownMenuTrigger'
  ],
  form: ['FormDescription', 'FormError', 'FormFieldArray', 'FormField', 'FormLabel'],
  input: ['InputControl', 'InputRoot'],
  kbd: ['Kbd'],
  label: ['Label'],
  layout: [
    'LayoutFooter',
    'LayoutHeader',
    'LayoutMain',
    'LayoutMobile',
    'LayoutRail',
    'LayoutRoot',
    'LayoutSidebar',
    'LayoutTab',
    'LayoutTrigger'
  ],
  link: ['Link'],
  list: ['ListContent', 'ListDescription', 'ListItem', 'ListRoot', 'ListTitle'],
  listbox: [
    'ListboxContent',
    'ListboxFilter',
    'ListboxGroupLabel',
    'ListboxGroup',
    'ListboxItemIndicator',
    'ListboxItem',
    'ListboxRoot',
    'ListboxVirtualizer'
  ],
  menu: [
    'MenuCheckboxGroup',
    'MenuCheckboxItem',
    'MenuContentImpl',
    'MenuContent',
    'MenuGroupLabel',
    'MenuGroup',
    'MenuItemImpl',
    'MenuItemIndicator',
    'MenuItem',
    'MenuRadioGroup',
    'MenuRadioItem',
    'MenuRoot',
    'MenuSubContent',
    'MenuSubTrigger',
    'MenuSub'
  ],
  navigationMenu: [
    'NavigationMenuContentImpl',
    'NavigationMenuContent',
    'NavigationMenuIndicator',
    'NavigationMenuItem',
    'NavigationMenuLink',
    'NavigationMenuList',
    'NavigationMenuRoot',
    'NavigationMenuSubList',
    'NavigationMenuTrigger',
    'NavigationMenuViewport'
  ],
  numberInput: ['NumberInputControl', 'NumberInputDecrement', 'NumberInputIncrement', 'NumberInputRoot'],
  pagination: [
    'PaginationEllipsis',
    'PaginationFirst',
    'PaginationLast',
    'PaginationListItem',
    'PaginationList',
    'PaginationNext',
    'PaginationPrev',
    'PaginationRoot'
  ],
  popover: [
    'PopoverAnchor',
    'PopoverArrow',
    'PopoverClose',
    'PopoverContent',
    'PopoverPortal',
    'PopoverRoot',
    'PopoverTrigger'
  ],
  popper: ['PopperAnchor', 'PopperArrow', 'PopperContent', 'PopperRoot'],
  portal: ['Portal'],
  primitive: ['Primitive'],
  radioGroup: ['RadioGroupControl', 'RadioGroupIndicator', 'RadioGroupItem', 'RadioGroupLabel', 'RadioGroupRoot'],
  rovingFocus: ['RovingFocusGroup', 'RovingFocusItem'],
  select: [
    'SelectArrow',
    'SelectContent',
    'SelectGroupLabel',
    'SelectGroup',
    'SelectItem',
    'SelectItemIndicator',
    'SelectItemText',
    'SelectPortal',
    'SelectRoot',
    'SelectScrollDownButton',
    'SelectScrollUpButton',
    'SelectSeparator',
    'SelectTrigger',
    'SelectTriggerIcon',
    'SelectValue',
    'SelectViewport'
  ],
  slot: ['Slot'],
  switch: ['SwitchControl', 'SwitchRoot', 'SwitchThumb'],
  tabs: ['TabsContent', 'TabsIndicator', 'TabsList', 'TabsRoot', 'TabsTrigger'],
  tag: ['Tag'],
  textarea: ['TextareaControl', 'TextareaCounter', 'TextareaRoot'],
  tooltip: ['TooltipArrow', 'TooltipContent', 'TooltipPortal', 'TooltipRoot', 'TooltipTrigger'],
  tree: ['TreeItem', 'TreeRoot', 'TreeVirtualizerItem', 'TreeVirtualizerRoot'],
  virtualizer: ['VirtualizerContent', 'VirtualizerItem', 'VirtualizerRoot'],
  visuallyHidden: ['VisuallyHiddenInput', 'VisuallyHidden']
};
