export const components = {
  accordion: ['SAccordion'],
  affix: ['SAffix'],
  alert: ['SAlert'],
  anchor: ['SAnchor'],
  arrow: ['SArrow'],
  aspectRatio: ['SAspectRatio'],
  autocomplete: ['SAutocomplete'],
  avatar: ['SAvatar'],
  backtop: ['SBacktop'],
  badge: ['SBadge'],
  bottomSheet: ['SBottomSheet'],
  breadcrumb: ['SBreadcrumbPage', 'SBreadcrumbEllipsis', 'SBreadcrumb'],
  button: ['SButton', 'SButtonLoading', 'SButtonIcon', 'SButtonLink', 'SButtonGroup'],
  calendar: ['SCalendar'],
  card: ['SCard', 'SCardCollapsibleTrigger'],
  carousel: ['SCarousel'],
  checkbox: ['SCheckboxGroup', 'SCheckbox', 'SCheckboxCardGroup', 'SCheckboxCard'],
  clipboard: ['SClipboard'],
  collapsible: ['SCollapsibleContent', 'SCollapsibleTrigger', 'SCollapsible'],
  colorArea: ['SColorArea'],
  colorField: ['SColorField'],
  colorPicker: ['SColorPicker'],
  colorSlider: ['SColorSlider'],
  colorSwatch: ['SColorSwatch'],
  colorSwatchPicker: ['SColorSwatchPicker'],
  combobox: ['SCombobox'],
  command: ['SCommand'],
  configProvider: ['SConfigProvider'],
  contextMenu: ['SContextMenuWrapper', 'SContextMenu', 'SContextMenuCheckbox', 'SContextMenuRadio'],
  dateField: ['SDateField'],
  datePicker: ['SDatePicker'],
  dateRangeField: ['SDateRangeField'],
  dateRangePicker: ['SDateRangePicker'],
  dialog: ['SDialog', 'SDialogProvider'],
  drawer: ['SDrawer'],
  dropdownMenu: ['SDropdownMenu', 'SDropdownMenuCheckbox', 'SDropdownMenuRadio', 'SDropdownMenuWrapper'],
  editable: ['SEditable'],
  empty: ['SEmpty'],
  form: ['SForm', 'SFormFieldBase'],
  hoverCard: ['SHoverCard'],
  icon: ['SIcon'],
  input: ['SInput'],
  inputNumber: ['SInputNumber'],
  inputOtp: ['SInputOtp'],
  kbd: ['SKbd'],
  label: ['SLabel'],
  layout: ['SLayoutTrigger', 'SLayout', 'SLayoutClassic'],
  link: ['SLink'],
  list: ['SList', 'SListItem'],
  menu: ['SMenuOptions', 'SMenuCheckboxOptions', 'SMenuRadioOptions'],
  menubar: ['SMenubar'],
  monthPicker: ['SMonthPicker'],
  monthRangePicker: ['SMonthRangePicker'],
  navigationMenu: ['SNavigationMenu'],
  pageTabs: ['SPageTabs'],
  pagination: ['SPagination'],
  password: ['SPassword'],
  popconfirm: ['SPopconfirm', 'SPopconfirmConfirm', 'SPopconfirmCancel'],
  popover: ['SPopover'],
  progress: ['SProgressProvider', 'SProgress', 'SProgressCircle'],
  radioGroup: ['SRadioGroup', 'SRadio', 'SRadioCard', 'SRadioCardGroup'],
  rangeCalendar: ['SRangeCalendar'],
  scrollArea: ['SScrollArea'],
  segment: ['SSegment'],
  select: ['SSelect'],
  separator: ['SSeparator'],
  skeleton: ['SSkeleton'],
  slider: ['SSlider'],
  spinner: ['SSpinner'],
  splitter: ['SSplitterGroup', 'SSplitterPanel', 'SSplitterResizeHandle'],
  stepper: ['SStepper'],
  switch: ['SSwitch'],
  table: ['STableRow', 'STableCell', 'STable'],
  tabs: ['STabs'],
  tag: ['STag'],
  tagsInput: [
    'STagsInputClear',
    'STagsInputInput',
    'STagsInputItem',
    'STagsInputItemText',
    'STagsInput',
    'STagsInputItemDelete'
  ],
  textarea: ['STextarea'],
  timeField: ['STimeField'],
  timePicker: ['STimePicker'],
  timeRangeField: ['STimeRangeField'],
  timeRangePicker: ['STimeRangePicker'],
  toast: ['SToastProvider'],
  toggle: ['SToggle'],
  toggleGroup: ['SToggleGroup', 'SToggleGroupItem'],
  toolbar: [
    'SToolbarButton',
    'SToolbarLink',
    'SToolbarSeparator',
    'SToolbarToggleGroup',
    'SToolbarToggleItem',
    'SToolbar'
  ],
  tooltip: ['STooltip'],
  tree: ['STreeItem', 'STreeVirtualizerItem', 'STree', 'STreeVirtualizer'],
  treeMenu: ['STreeMenu', 'STreeMenuStyledItem'],
  virtualizer: ['SVirtualizerItem', 'SVirtualizer'],
  yearPicker: ['SYearPicker'],
  yearRangePicker: ['SYearRangePicker']
};
