export const components = {
  accordion: ['SAccordion'],
  alert: ['SAlert'],
  alertDialog: ['SAlertDialog', 'SAlertDialogCancel', 'SAlertDialogAction'],
  arrow: ['SArrow'],
  aspectRatio: ['SAspectRatio'],
  avatar: ['SAvatar'],
  badge: ['SBadge'],
  breadcrumb: ['SBreadcrumb', 'SBreadcrumbPage', 'SBreadcrumbEllipsis'],
  button: ['SButton', 'SButtonLoading', 'SButtonIcon', 'SButtonLink', 'SButtonGroup'],
  card: ['SCard'],
  checkbox: ['SCheckboxGroup', 'SCheckbox', 'SCheckboxCardGroup', 'SCheckboxCard'],
  collapsible: ['SCollapsible', 'SCollapsibleContent', 'SCollapsibleTrigger'],
  command: ['SCommand'],
  configProvider: ['SConfigProvider'],
  contextMenu: ['SContextMenu', 'SContextMenuCheckbox', 'SContextMenuRadio', 'SContextMenuWrapper'],
  dialog: ['SDialog', 'SDialogClose', 'SDialogPure'],
  drawer: ['SDrawer', 'SDrawerClose'],
  dropdownMenu: ['SDropdownMenu', 'SDropdownMenuCheckbox', 'SDropdownMenuRadio', 'SDropdownMenuWrapper'],
  form: ['SForm', 'SFormField', 'SFormFieldArray'],
  input: ['SInput'],
  icon: ['SIcon'],
  kbd: ['SKbd'],
  label: ['SLabel'],
  layout: ['SLayout', 'SLayoutTrigger'],
  link: ['SLink'],
  list: ['SList', 'SListItem'],
  menu: ['SMenuOption', 'SMenuOptions', 'SMenuCheckboxOptions', 'SMenuRadioOptions'],
  navigationMenu: ['SNavigationMenu'],
  numberInput: ['SNumberInput'],
  pageTabs: ['SPageTabs'],
  pagination: ['SPagination'],
  password: ['SPassword'],
  popover: ['SPopover'],
  radioGroup: ['SRadioGroup', 'SRadio', 'SRadioCard', 'SRadioCardGroup'],
  segment: ['SSegment'],
  select: ['SSelect'],
  separator: ['SSeparator'],
  switch: ['SSwitch'],
  tabs: ['STabs'],
  tag: ['STag'],
  textarea: ['STextarea'],
  toast: ['SToast', 'SToastAction', 'SToastClose'],
  tooltip: ['STooltip'],
  tree: ['STree', 'STreeVirtualizer'],
  treeMenu: ['STreeMenu', 'STreeMenuStyledItem'],
  virtualizer: ['SVirtualizer']
};
