/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/app-header.vue')['default']
    AppLogo: typeof import('./../components/app-logo.vue')['default']
    CodeBlock: typeof import('./../components/code-block.vue')['default']
    DataTable: typeof import('./../components/tables/data-table.vue')['default']
    DocMd: typeof import('./../components/doc-md.vue')['default']
    HeaderNav: typeof import('./../components/header-nav.vue')['default']
    LocaleToggler: typeof import('./../components/locale-toggler.vue')['default']
    PlaygroundGallery: typeof import('./../components/playground-gallery.vue')['default']
    PlaygroundTooltip: typeof import('./../components/playground-tooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButtonIcon: typeof import('@soybeanjs/ui')['SButtonIcon']
    SButtonLink: typeof import('@soybeanjs/ui')['SButtonLink']
    SCommand: typeof import('@soybeanjs/ui')['SCommand']
    SConfigProvider: typeof import('@soybeanjs/ui')['SConfigProvider']
    SDialogPure: typeof import('@soybeanjs/ui')['SDialogPure']
    SDrawer: typeof import('@soybeanjs/ui')['SDrawer']
    SDropdownMenuRadio: typeof import('@soybeanjs/ui')['SDropdownMenuRadio']
    SearchDocument: typeof import('./../components/search-document.vue')['default']
    SIcon: typeof import('@soybeanjs/ui')['SIcon']
    SiderMenu: typeof import('./../components/sider-menu.vue')['default']
    SKbd: typeof import('@soybeanjs/ui')['SKbd']
    SLink: typeof import('@soybeanjs/ui')['SLink']
    SNavigationMenu: typeof import('@soybeanjs/ui')['SNavigationMenu']
    SPopover: typeof import('@soybeanjs/ui')['SPopover']
    SSeparator: typeof import('@soybeanjs/ui')['SSeparator']
    SSwitch: typeof import('@soybeanjs/ui')['SSwitch']
    STag: typeof import('@soybeanjs/ui')['STag']
    STreeMenu: typeof import('@soybeanjs/ui')['STreeMenu']
    ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
    ToolBar: typeof import('./../components/tool-bar.vue')['default']
    TypeData: typeof import('./../components/tables/type-data.vue')['default']
    TypeTable: typeof import('./../components/tables/type-table.vue')['default']
  }
}

// For TSX support
declare global {
  const AppHeader: typeof import('./../components/app-header.vue')['default']
  const AppLogo: typeof import('./../components/app-logo.vue')['default']
  const CodeBlock: typeof import('./../components/code-block.vue')['default']
  const DataTable: typeof import('./../components/tables/data-table.vue')['default']
  const DocMd: typeof import('./../components/doc-md.vue')['default']
  const HeaderNav: typeof import('./../components/header-nav.vue')['default']
  const LocaleToggler: typeof import('./../components/locale-toggler.vue')['default']
  const PlaygroundGallery: typeof import('./../components/playground-gallery.vue')['default']
  const PlaygroundTooltip: typeof import('./../components/playground-tooltip.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SButtonIcon: typeof import('@soybeanjs/ui')['SButtonIcon']
  const SButtonLink: typeof import('@soybeanjs/ui')['SButtonLink']
  const SCommand: typeof import('@soybeanjs/ui')['SCommand']
  const SConfigProvider: typeof import('@soybeanjs/ui')['SConfigProvider']
  const SDialogPure: typeof import('@soybeanjs/ui')['SDialogPure']
  const SDrawer: typeof import('@soybeanjs/ui')['SDrawer']
  const SDropdownMenuRadio: typeof import('@soybeanjs/ui')['SDropdownMenuRadio']
  const SearchDocument: typeof import('./../components/search-document.vue')['default']
  const SIcon: typeof import('@soybeanjs/ui')['SIcon']
  const SiderMenu: typeof import('./../components/sider-menu.vue')['default']
  const SKbd: typeof import('@soybeanjs/ui')['SKbd']
  const SLink: typeof import('@soybeanjs/ui')['SLink']
  const SNavigationMenu: typeof import('@soybeanjs/ui')['SNavigationMenu']
  const SPopover: typeof import('@soybeanjs/ui')['SPopover']
  const SSeparator: typeof import('@soybeanjs/ui')['SSeparator']
  const SSwitch: typeof import('@soybeanjs/ui')['SSwitch']
  const STag: typeof import('@soybeanjs/ui')['STag']
  const STreeMenu: typeof import('@soybeanjs/ui')['STreeMenu']
  const ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
  const ToolBar: typeof import('./../components/tool-bar.vue')['default']
  const TypeData: typeof import('./../components/tables/type-data.vue')['default']
  const TypeTable: typeof import('./../components/tables/type-table.vue')['default']
}