/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LocaleToggler: typeof import('./../components/locale-toggler.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('@soybeanjs/ui')['SButton']
    SButtonIcon: typeof import('@soybeanjs/ui')['SButtonIcon']
    SButtonLink: typeof import('@soybeanjs/ui')['SButtonLink']
    SCard: typeof import('@soybeanjs/ui')['SCard']
    SConfigProvider: typeof import('@soybeanjs/ui')['SConfigProvider']
    SDialog: typeof import('@soybeanjs/ui')['SDialog']
    SDropdownMenu: typeof import('@soybeanjs/ui')['SDropdownMenu']
    SDropdownMenuRadio: typeof import('@soybeanjs/ui')['SDropdownMenuRadio']
    SIcon: typeof import('@soybeanjs/ui')['SIcon']
    SSwitch: typeof import('@soybeanjs/ui')['SSwitch']
    ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
    ToolBar: typeof import('./../components/tool-bar.vue')['default']
  }
}

// For TSX support
declare global {
  const LocaleToggler: typeof import('./../components/locale-toggler.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SButton: typeof import('@soybeanjs/ui')['SButton']
  const SButtonIcon: typeof import('@soybeanjs/ui')['SButtonIcon']
  const SButtonLink: typeof import('@soybeanjs/ui')['SButtonLink']
  const SCard: typeof import('@soybeanjs/ui')['SCard']
  const SConfigProvider: typeof import('@soybeanjs/ui')['SConfigProvider']
  const SDialog: typeof import('@soybeanjs/ui')['SDialog']
  const SDropdownMenu: typeof import('@soybeanjs/ui')['SDropdownMenu']
  const SDropdownMenuRadio: typeof import('@soybeanjs/ui')['SDropdownMenuRadio']
  const SIcon: typeof import('@soybeanjs/ui')['SIcon']
  const SSwitch: typeof import('@soybeanjs/ui')['SSwitch']
  const ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
  const ToolBar: typeof import('./../components/tool-bar.vue')['default']
}