export const components = {
  accordion: [
    'SAccordionContent',
    'SAccordionContentBody',
    'SAccordionHeader',
    'SAccordionItem',
    'SAccordionRoot',
    'SAccordionTrigger',
    'SAccordion'
  ],
  alert: ['SAlertRoot', 'SAlertHeader', 'SAlertTitleRoot', 'SAlertTitle', 'SAlertDescription', 'SAlert'],
  alertDialog: [
    'SAlertDialogAction',
    'SAlertDialogCancel',
    'SAlertDialogContent',
    'SAlertDialogDescription',
    'SAlertDialogOverlay',
    'SAlertDialogPortal',
    'SAlertDialogRoot',
    'SAlertDialogTitle',
    'SAlertDialogTrigger',
    'SAlertDialogHeader',
    'SAlertDialogFooter',
    'SAlertDialog'
  ],
  aspectRatio: ['SAspectRatio'],
  avatar: ['SAvatarFallback', 'SAvatarImage', 'SAvatarRoot', 'SAvatar'],
  badge: ['SBadgeRoot', 'SBadgeContent', 'SBadge'],
  breadcrumb: [
    'SBreadcrumbRoot',
    'SBreadcrumbList',
    'SBreadcrumbItem',
    'SBreadcrumbPage',
    'SBreadcrumbLink',
    'SBreadcrumbEllipsis',
    'SBreadcrumbSeparator',
    'SBreadcrumb'
  ],
  button: ['SButton', 'SButtonGroup', 'SButtonIcon', 'SButtonLink', 'SLoadingButton'],
  // calendar: [
  //   'SCalendarCellTrigger',
  //   'SCalendarCell',
  //   'SCalendarGridBody',
  //   'SCalendarGridHead',
  //   'SCalendarGridRow',
  //   'SCalendarGrid',
  //   'SCalendarHeadCell',
  //   'SCalendarHeader',
  //   'SCalendarHeading',
  //   'SCalendarNext',
  //   'SCalendarPrev',
  //   'SCalendarRoot'
  // ],
  card: ['SCardRoot', 'SCardHeader', 'SCardTitleRoot', 'SCardTitle', 'SCardBody', 'SCardFooter', 'SCard'],
  carousel: ['SCarouselRoot', 'SCarouselContent', 'SCarouselItem', 'SCarouselNext', 'SCarouselPrevious', 'SCarousel'],
  checkbox: [
    'SCheckboxGroupRoot',
    'SCheckboxControl',
    'SCheckboxIndicator',
    'SCheckboxRoot',
    'SCheckbox',
    'SCheckboxGroup'
  ],
  collapsible: ['SCollapsibleContent', 'SCollapsibleRoot', 'SCollapsibleTrigger', 'SCollapsible'],
  combobox: [
    'SComboboxRoot',
    'SComboboxAnchor',
    'SComboboxEmpty',
    'SComboboxGroup',
    'SComboboxGroupLabel',
    'SComboboxInput',
    'SComboboxItem',
    'SComboboxList',
    'SComboboxOption',
    'SComboboxSearchIcon',
    'SComboboxSeparator',
    'SComboboxSingleOption',
    'SComboboxTrigger',
    'SCombobox'
  ],
  command: [
    'SCommandRoot',
    'SCommandInput',
    'SCommandList',
    'SCommandEmpty',
    'SCommandGroup',
    'SCommandGroupLabel',
    'SCommandItem',
    'SCommandSeparator',
    'SCommandShortcut',
    'SCommandDialog',
    'SCommandOption',
    'SCommandSingleOption',
    'SCommand'
  ],
  // configProvider: ['SConfigProvider'],
  contextMenu: [
    'SContextMenuContent',
    'SContextMenuOption',
    'SContextMenuPortalContent',
    'SContextMenuSubContent',
    'SContextMenuLabel',
    'SContextMenuSeparator',
    'SContextMenuItem',
    'SContextMenuItemLink',
    'SContextMenuItemLinkIcon',
    'SContextMenuShortcut',
    'SContextMenuSubTrigger',
    'SContextMenu'
  ],
  // dateField: ['DateFieldInput', 'DateFieldRoot'],
  // datePicker: [
  //   'DatePickerAnchor',
  //   'DatePickerArrow',
  //   'DatePickerCalendar',
  //   'DatePickerCellTrigger',
  //   'DatePickerCell',
  //   'DatePickerClose',
  //   'DatePickerContent',
  //   'DatePickerField',
  //   'DatePickerGridBody',
  //   'DatePickerGridHead',
  //   'DatePickerGridRow',
  //   'DatePickerGrid',
  //   'DatePickerHeadCell',
  //   'DatePickerHeader',
  //   'DatePickerHeading',
  //   'DatePickerInput',
  //   'DatePickerNext',
  //   'DatePickerPrev',
  //   'DatePickerRoot',
  //   'DatePickerTrigger'
  // ],
  // dateRangeField: ['DateRangeFieldInput', 'DateRangeFieldRoot'],
  // dateRangePicker: [
  //   'DateRangePickerAnchor',
  //   'DateRangePickerArrow',
  //   'DateRangePickerCalendar',
  //   'DateRangePickerCellTrigger',
  //   'DateRangePickerCell',
  //   'DateRangePickerClose',
  //   'DateRangePickerContent',
  //   'DateRangePickerField',
  //   'DateRangePickerGridBody',
  //   'DateRangePickerGridHead',
  //   'DateRangePickerGridRow',
  //   'DateRangePickerGrid',
  //   'DateRangePickerHeadCell',
  //   'DateRangePickerHeader',
  //   'DateRangePickerHeading',
  //   'DateRangePickerInput',
  //   'DateRangePickerNext',
  //   'DateRangePickerPrev',
  //   'DateRangePickerRoot',
  //   'DateRangePickerTrigger'
  // ],
  dialog: [
    'SDialogClose',
    'SDialogContent',
    'SDialogDescription',
    'SDialogOverlay',
    'SDialogPortal',
    'SDialogRoot',
    'SDialogTitle',
    'SDialogTrigger',
    'SDialogHeader',
    'SDialogFooter',
    'SDialog'
  ],
  drawer: [
    'SDrawerOverlay',
    'SDrawerContent',
    'SDrawerContentBody',
    'SDrawerKnob',
    'SDrawerRoot',
    'SDrawerClose',
    'SDrawerPortal',
    'SDrawerFooter',
    'SDrawer'
  ],
  dropdownMenu: ['SDropdownMenu', 'SDropdownMenuCheckbox', 'SDropdownMenuRadio'],
  form: [
    'SFormControl',
    'SFormItem',
    'SFormLabel',
    'SFormDescription',
    'SFormMessage',
    'SFormField',
    'SFormFieldArray'
  ],
  hoverCard: [
    'SHoverCardArrow',
    'SHoverCardContent',
    'SHoverCardPortal',
    'SHoverCardRoot',
    'SHoverCardTrigger',
    'SHoverCard'
  ],
  input: ['SInput'],
  keyboardKey: ['SKeyboardKey', 'SKeyboardKeyGroup'],
  label: ['SLabel'],
  link: ['SLink'],
  menu: [
    'SMenuPortal',
    'SMenuArrow',
    'SMenuContent',
    'SMenuSubContent',
    'SMenuSubTrigger',
    'SMenuItem',
    'SMenuItemIndicator',
    'SMenuItemLink',
    'SMenuItemLinkIcon',
    'SMenuLabel',
    'SMenuShortcut',
    'SMenuCheckboxItem',
    'SMenuRadioItem',
    'SMenuRadioIndicatorIcon',
    'SMenuSeparator',
    'SMenuOption',
    'SMenuCheckboxGroup',
    'SMenuRadioGroup',
    'SMenuPortalContent',
    'SMenu',
    'SMenuCheckbox',
    'SMenuRadio'
  ],
  menubar: [
    'SMenubarRoot',
    'SMenubarContent',
    'SMenubarItem',
    'SMenubarMenu',
    'SMenubarOption',
    'SMenubarPortalContent',
    'SMenubarSubContent',
    'SMenubarSubTrigger',
    'SMenubarTrigger',
    'SMenubarTriggerLink',
    'SMenubarTriggerOption',
    'SMenubar'
  ],
  navigationMenu: [
    'SNavigationMenuRoot',
    'SNavigationMenuViewport',
    'SNavigationMenuList',
    'SNavigationMenuContent',
    'SNavigationMenuItem',
    'SNavigationMenuTrigger',
    'SNavigationMenuLink',
    'SNavigationMenuIndicator',
    'SNavigationMenuSub',
    'SNavigationMenu'
  ],
  numberField: [
    'SNumberFieldDecrement',
    'SNumberFieldIncrement',
    'SNumberFieldInput',
    'SNumberFieldRoot',
    'SNumberField'
  ],
  pagination: [
    'SPaginationRoot',
    'SPaginationList',
    'SPaginationListItem',
    'SPaginationFirst',
    'SPaginationLast',
    'SPaginationNext',
    'SPaginationPrev',
    'SPaginationButton',
    'SPaginationEllipsis',
    'SPagination'
  ],
  pinInput: ['SPinInputRoot', 'SPinInputItem', 'SPinInputSeparator', 'SPinInput'],
  popover: [
    'SPopover',
    'SPopoverRoot',
    'SPopoverTrigger',
    'SPopoverContent',
    'SPopoverPortal',
    'SPopoverAnchor',
    'SPopoverArrow',
    'SPopoverClose'
  ],
  progress: ['SProgressRoot', 'SProgressIndicator', 'SProgress'],
  radioGroup: ['SRadioRoot', 'SRadioControl', 'SRadioIndicator', 'SRadio', 'SRadioGroup'],
  // rangeCalendar: [
  //   'RangeCalendarCellTrigger',
  //   'RangeCalendarCell',
  //   'RangeCalendarGridBody',
  //   'RangeCalendarGridHead',
  //   'RangeCalendarGridRow',
  //   'RangeCalendarGrid',
  //   'RangeCalendarHeadCell',
  //   'RangeCalendarHeader',
  //   'RangeCalendarHeading',
  //   'RangeCalendarNext',
  //   'RangeCalendarPrev',
  //   'RangeCalendarRoot'
  // ],
  resizable: ['SResizablePanel', 'SResizableHandle', 'SResizablePanelGroup'],
  scrollArea: [
    'SScrollAreaRoot',
    'SScrollAreaViewport',
    'SScrollAreaScrollbar',
    'SScrollAreaThumb',
    'SScrollAreaCorner',
    'SScrollArea'
  ],
  segment: [
    'SSegmentRoot',
    'SSegmentTriggerRoot',
    'SSegmentTrigger',
    'SSegmentIndicatorRoot',
    'SSegmentIndicator',
    'SSegment'
  ],
  select: [
    'SSelectRoot',
    'SSelectTrigger',
    'SSelectValue',
    'SSelectIcon',
    'SSelectPortal',
    'SSelectContent',
    'SSelectScrollUpButton',
    'SSelectScrollDownButton',
    'SSelectViewport',
    'SSelectGroup',
    'SSelectItem',
    'SSelectItemText',
    'SSelectItemIndicator',
    'SSelectSeparator',
    'SSelectLabel',
    'SSelect',
    'SSelectOption'
  ],
  separator: ['SSeparatorRoot', 'SSeparatorLabel', 'SSeparator'],
  sheet: ['SSheetContent', 'SSheet'],
  skeleton: ['SSkeleton'],
  slider: ['SSliderRoot', 'SSliderTrack', 'SSliderRange', 'SSliderThumb', 'SSlider'],
  stepper: [
    'SStepperRoot',
    'SStepperDescription',
    'SStepperIndicator',
    'SStepperItem',
    'SStepperSeparator',
    'SStepperTitle',
    'SStepperTrigger',
    'SStepper'
  ],
  switch: ['SSwitchRoot', 'SSwitchThumb', 'SSwitch'],
  tabs: ['STabsRoot', 'STabsList', 'STabsTrigger', 'STabsIndicatorRoot', 'STabsIndicator', 'STabsContent', 'STabs'],
  tag: ['STag'],
  tagsInput: [
    'STagsInputRoot',
    'STagsInputInput',
    'STagsInputItem',
    'STagsInputItemText',
    'STagsInputItemDelete',
    'STagsInput'
  ],
  textarea: ['STextareaRoot', 'STextareaContent', 'STextareaCount', 'STextarea'],
  // timeField: ['STimeFieldInput', 'STimeFieldRoot'],
  toast: ['SToastProvider', 'SToastAction'],
  toggle: ['SToggle'],
  toggleGroup: ['SToggleGroupRoot', 'SToggleGroupItem', 'SToggleGroup'],
  // toolbar: [
  //   'SToolbarButton',
  //   'SToolbarLink',
  //   'ToolbarRoot',
  //   'ToolbarSeparator',
  //   'ToolbarToggleGroup',
  //   'ToolbarToggleItem'
  // ],
  tooltip: ['STooltip', 'STooltipProvider', 'STooltipRoot', 'STooltipTrigger', 'STooltipContent', 'STooltipArrow']
  // tree: ['STreeItem', 'STreeRoot', 'STreeVirtualizer'],
};
