/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/[name]': RouteRecordInfo<
      '/admin/[name]',
      '/admin/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/admin/installation': RouteRecordInfo<
      '/admin/installation',
      '/admin/installation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/quick-start': RouteRecordInfo<
      '/admin/quick-start',
      '/admin/quick-start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chart/': RouteRecordInfo<
      '/chart/',
      '/chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chart/[name]': RouteRecordInfo<
      '/chart/[name]',
      '/chart/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/chart/installation': RouteRecordInfo<
      '/chart/installation',
      '/chart/installation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chart/quick-start': RouteRecordInfo<
      '/chart/quick-start',
      '/chart/quick-start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/': RouteRecordInfo<
      '/components/',
      '/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/[name]': RouteRecordInfo<
      '/components/[name]',
      '/components/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/overview/': RouteRecordInfo<
      '/overview/',
      '/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/overview/installation': RouteRecordInfo<
      '/overview/installation',
      '/overview/installation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/overview/introduction': RouteRecordInfo<
      '/overview/introduction',
      '/overview/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/overview/llms': RouteRecordInfo<
      '/overview/llms',
      '/overview/llms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/overview/quick-start': RouteRecordInfo<
      '/overview/quick-start',
      '/overview/quick-start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/overview/skills': RouteRecordInfo<
      '/overview/skills',
      '/overview/skills',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/overview/theming': RouteRecordInfo<
      '/overview/theming',
      '/overview/theming',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/releases': RouteRecordInfo<
      '/releases',
      '/releases',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sbean': RouteRecordInfo<
      '/sbean',
      '/sbean',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ui-x/': RouteRecordInfo<
      '/ui-x/',
      '/ui-x',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ui-x/[name]': RouteRecordInfo<
      '/ui-x/[name]',
      '/ui-x/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/ui-x/installation': RouteRecordInfo<
      '/ui-x/installation',
      '/ui-x/installation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ui-x/quick-start': RouteRecordInfo<
      '/ui-x/quick-start',
      '/ui-x/quick-start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/[name].vue': {
      routes:
        | '/admin/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/admin/installation.vue': {
      routes:
        | '/admin/installation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/quick-start.vue': {
      routes:
        | '/admin/quick-start'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/chart/index.vue': {
      routes:
        | '/chart/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/chart/[name].vue': {
      routes:
        | '/chart/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/chart/installation.vue': {
      routes:
        | '/chart/installation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/chart/quick-start.vue': {
      routes:
        | '/chart/quick-start'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/index.vue': {
      routes:
        | '/components/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/[name].vue': {
      routes:
        | '/components/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/overview/index.vue': {
      routes:
        | '/overview/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/overview/installation.vue': {
      routes:
        | '/overview/installation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/overview/introduction.vue': {
      routes:
        | '/overview/introduction'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/overview/llms.vue': {
      routes:
        | '/overview/llms'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/overview/quick-start.vue': {
      routes:
        | '/overview/quick-start'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/overview/skills.vue': {
      routes:
        | '/overview/skills'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/overview/theming.vue': {
      routes:
        | '/overview/theming'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/releases.vue': {
      routes:
        | '/releases'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sbean.vue': {
      routes:
        | '/sbean'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-x/index.vue': {
      routes:
        | '/ui-x/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-x/[name].vue': {
      routes:
        | '/ui-x/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/ui-x/installation.vue': {
      routes:
        | '/ui-x/installation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-x/quick-start.vue': {
      routes:
        | '/ui-x/quick-start'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
