export const components = {
  accordion: ['AccordionContent', 'AccordionHeader', 'AccordionItem', 'AccordionRoot', 'AccordionTrigger'],
  alertDialog: [
    'AlertDialogAction',
    'AlertDialogCancel',
    'AlertDialogContent',
    'AlertDialogDescription',
    'AlertDialogOverlay',
    'AlertDialogPortal',
    'AlertDialogRoot',
    'AlertDialogTitle',
    'AlertDialogTrigger'
  ],
  arrow: ['Arrow'],
  aspectRatio: ['AspectRatio'],
  avatar: ['AvatarFallback', 'AvatarImage', 'AvatarRoot'],
  calendar: [
    'CalendarCellTrigger',
    'CalendarCell',
    'CalendarGridBody',
    'CalendarGridHead',
    'CalendarGridRow',
    'CalendarGrid',
    'CalendarHeadCell',
    'CalendarHeader',
    'CalendarHeading',
    'CalendarNext',
    'CalendarPrev',
    'CalendarRoot'
  ],
  checkbox: ['CheckboxGroupRoot', 'CheckboxIndicator', 'CheckboxRoot'],
  collapsible: ['CollapsibleContent', 'CollapsibleRoot', 'CollapsibleTrigger'],
  combobox: [
    'ComboboxAnchor',
    'ComboboxArrow',
    'ComboboxCancel',
    'ComboboxContentImpl',
    'ComboboxContent',
    'ComboboxEmpty',
    'ComboboxGroup',
    'ComboboxInput',
    'ComboboxItemIndicator',
    'ComboboxItem',
    'ComboboxLabel',
    'ComboboxPortal',
    'ComboboxRoot',
    'ComboboxSeparator',
    'ComboboxTrigger',
    'ComboboxViewport',
    'ComboboxVirtualizer'
  ],
  configProvider: ['ConfigProvider'],
  contextMenu: ['ContextMenuContent', 'ContextMenuRoot', 'ContextMenuSubContent', 'ContextMenuTrigger'],
  dateField: ['DateFieldInput', 'DateFieldRoot'],
  datePicker: [
    'DatePickerAnchor',
    'DatePickerArrow',
    'DatePickerCalendar',
    'DatePickerCellTrigger',
    'DatePickerCell',
    'DatePickerClose',
    'DatePickerContent',
    'DatePickerField',
    'DatePickerGridBody',
    'DatePickerGridHead',
    'DatePickerGridRow',
    'DatePickerGrid',
    'DatePickerHeadCell',
    'DatePickerHeader',
    'DatePickerHeading',
    'DatePickerInput',
    'DatePickerNext',
    'DatePickerPrev',
    'DatePickerRoot',
    'DatePickerTrigger'
  ],
  dateRangeField: ['DateRangeFieldInput', 'DateRangeFieldRoot'],
  dateRangePicker: [
    'DateRangePickerAnchor',
    'DateRangePickerArrow',
    'DateRangePickerCalendar',
    'DateRangePickerCellTrigger',
    'DateRangePickerCell',
    'DateRangePickerClose',
    'DateRangePickerContent',
    'DateRangePickerField',
    'DateRangePickerGridBody',
    'DateRangePickerGridHead',
    'DateRangePickerGridRow',
    'DateRangePickerGrid',
    'DateRangePickerHeadCell',
    'DateRangePickerHeader',
    'DateRangePickerHeading',
    'DateRangePickerInput',
    'DateRangePickerNext',
    'DateRangePickerPrev',
    'DateRangePickerRoot',
    'DateRangePickerTrigger'
  ],
  dialog: [
    'DialogClose',
    'DialogContentImpl',
    'DialogContentModal',
    'DialogContentNonModal',
    'DialogContent',
    'DialogDescription',
    'DialogOverlayImpl',
    'DialogOverlay',
    'DialogPortal',
    'DialogRoot',
    'DialogTitle',
    'DialogTrigger'
  ],
  dismissableLayer: ['DismissableLayerBranch', 'DismissableLayer'],
  drawer: ['DrawerContent', 'DrawerOverlay', 'DrawerRootNested', 'DrawerRoot'],
  dropdownMenu: ['DropdownMenuContent', 'DropdownMenuRoot', 'DropdownMenuSubContent', 'DropdownMenuTrigger'],
  editable: [
    'EditableArea',
    'EditableCancelTrigger',
    'EditableEditTrigger',
    'EditableInput',
    'EditablePreview',
    'EditableRoot',
    'EditableSubmitTrigger'
  ],
  focusGuards: ['FocusGuards'],
  focusScope: ['FocusScope'],
  hoverCard: [
    'HoverCardArrow',
    'HoverCardContentImpl',
    'HoverCardContent',
    'HoverCardPortal',
    'HoverCardRoot',
    'HoverCardTrigger'
  ],
  label: ['Label'],
  listbox: [
    'ListboxContent',
    'ListboxFilter',
    'ListboxGroupLabel',
    'ListboxGroup',
    'ListboxItemIndicator',
    'ListboxItem',
    'ListboxRoot',
    'ListboxVirtualizer'
  ],
  menu: [
    'MenuCheckboxItem',
    'MenuContentImpl',
    'MenuContent',
    'MenuGroup',
    'MenuItemImpl',
    'MenuItemIndicator',
    'MenuItem',
    'MenuLabel',
    'MenuPortal',
    'MenuRadioGroup',
    'MenuRadioItem',
    'MenuRootContentModal',
    'MenuRootContentNonModal',
    'MenuRoot',
    'MenuSeparator',
    'MenuSubContent',
    'MenuSubTrigger',
    'MenuSub'
  ],
  menubar: ['MenubarContent', 'MenubarMenu', 'MenubarRoot', 'MenubarSubContent', 'MenubarSubTrigger', 'MenubarTrigger'],
  navigationMenu: [
    'NavigationMenuContentImpl',
    'NavigationMenuContent',
    'NavigationMenuIndicator',
    'NavigationMenuItem',
    'NavigationMenuLink',
    'NavigationMenuList',
    'NavigationMenuRoot',
    'NavigationMenuSub',
    'NavigationMenuTrigger',
    'NavigationMenuViewport'
  ],
  numberField: ['NumberFieldDecrement', 'NumberFieldIncrement', 'NumberFieldInput', 'NumberFieldRoot'],
  pagination: [
    'PaginationEllipsis',
    'PaginationFirst',
    'PaginationLast',
    'PaginationListItem',
    'PaginationList',
    'PaginationNext',
    'PaginationPrev',
    'PaginationRoot'
  ],
  pinInput: ['PinInputInput', 'PinInputRoot'],
  popover: [
    'PopoverAnchor',
    'PopoverArrow',
    'PopoverClose',
    'PopoverContentImpl',
    'PopoverContentModal',
    'PopoverContentNonModal',
    'PopoverContent',
    'PopoverPortal',
    'PopoverRoot',
    'PopoverTrigger'
  ],
  popper: ['PopperAnchor', 'PopperArrow', 'PopperContent', 'PopperRoot'],
  progress: ['ProgressIndicator', 'ProgressRoot'],
  radioGroup: ['RadioGroupIndicator', 'RadioGroupItem', 'RadioGroupRoot', 'Radio'],
  rangeCalendar: [
    'RangeCalendarCellTrigger',
    'RangeCalendarCell',
    'RangeCalendarGridBody',
    'RangeCalendarGridHead',
    'RangeCalendarGridRow',
    'RangeCalendarGrid',
    'RangeCalendarHeadCell',
    'RangeCalendarHeader',
    'RangeCalendarHeading',
    'RangeCalendarNext',
    'RangeCalendarPrev',
    'RangeCalendarRoot'
  ],
  rovingFocus: ['RovingFocusGroup', 'RovingFocusItem'],
  scrollArea: [
    'ScrollAreaCornerImpl',
    'ScrollAreaCorner',
    'ScrollAreaRoot',
    'ScrollAreaScrollbarAuto',
    'ScrollAreaScrollbarHover',
    'ScrollAreaScrollbarImpl',
    'ScrollAreaScrollbarScroll',
    'ScrollAreaScrollbarVisible',
    'ScrollAreaScrollbarX',
    'ScrollAreaScrollbarY',
    'ScrollAreaScrollbar',
    'ScrollAreaThumb',
    'ScrollAreaViewport'
  ],
  select: [
    'BubbleSelect',
    'SelectArrow',
    'SelectContentImpl',
    'SelectContent',
    'SelectGroup',
    'SelectIcon',
    'SelectItemAlignedPosition',
    'SelectItemIndicator',
    'SelectItemText',
    'SelectItem',
    'SelectLabel',
    'SelectPopperPosition',
    'SelectPortal',
    'SelectProvider',
    'SelectRoot',
    'SelectScrollButtonImpl',
    'SelectScrollDownButton',
    'SelectScrollUpButton',
    'SelectSeparator',
    'SelectTrigger',
    'SelectValue',
    'SelectViewport'
  ],
  separator: ['Separator'],
  slider: [
    'SliderHorizontal',
    'SliderImpl',
    'SliderRange',
    'SliderRoot',
    'SliderThumbImpl',
    'SliderThumb',
    'SliderTrack',
    'SliderVertical'
  ],
  splitter: ['SplitterGroup', 'SplitterPanel', 'SplitterResizeHandle'],
  stepper: [
    'StepperDescription',
    'StepperIndicator',
    'StepperItem',
    'StepperRoot',
    'StepperSeparator',
    'StepperTitle',
    'StepperTrigger'
  ],
  switch: ['SwitchRoot', 'SwitchThumb'],
  tabs: ['TabsContent', 'TabsIndicator', 'TabsList', 'TabsRoot', 'TabsTrigger'],
  tagsInput: [
    'TagsInputClear',
    'TagsInputInput',
    'TagsInputItemDelete',
    'TagsInputItemText',
    'TagsInputItem',
    'TagsInputRoot'
  ],
  teleport: ['Teleport'],
  timeField: ['TimeFieldInput', 'TimeFieldRoot'],
  toast: [
    'FocusProxy',
    'ToastAction',
    'ToastAnnounceExclude',
    'ToastAnnounce',
    'ToastClose',
    'ToastDescription',
    'ToastPortal',
    'ToastProvider',
    'ToastRootImpl',
    'ToastRoot',
    'ToastTitle',
    'ToastViewport'
  ],
  toggle: ['Toggle'],
  toggleGroup: ['ToggleGroupItem', 'ToggleGroupRoot'],
  toolbar: [
    'ToolbarButton',
    'ToolbarLink',
    'ToolbarRoot',
    'ToolbarSeparator',
    'ToolbarToggleGroup',
    'ToolbarToggleItem'
  ],
  tooltip: [
    'TooltipArrow',
    'TooltipContentHoverable',
    'TooltipContentImpl',
    'TooltipContent',
    'TooltipPortal',
    'TooltipProvider',
    'TooltipRoot',
    'TooltipTrigger'
  ],
  tree: ['TreeItem', 'TreeRoot', 'TreeVirtualizer'],
  viewport: ['Viewport'],
  visuallyHidden: ['VisuallyHiddenInputBubble', 'VisuallyHiddenInput', 'VisuallyHidden']
};
