export const components = {
  accordion: ['SAccordion'],
  affix: ['SAffix'],
  alert: ['SAlert'],
  anchor: ['SAnchor'],
  arrow: ['SArrow'],
  aspectRatio: ['SAspectRatio'],
  autocomplete: ['SAutocomplete'],
  avatar: ['SAvatar'],
  backtop: ['SBacktop'],
  badge: ['SBadge'],
  bottomSheet: ['SBottomSheet'],
  breadcrumb: ['SBreadcrumb', 'SBreadcrumbPage', 'SBreadcrumbEllipsis'],
  button: ['SButton', 'SButtonLoading', 'SButtonIcon', 'SButtonLink', 'SButtonGroup'],
  calendar: ['SCalendar'],
  calendarRange: ['SCalendarRange'],
  card: ['SCard', 'SCardCollapsibleTrigger'],
  carousel: ['SCarousel'],
  cascader: ['SCascader'],
  checkbox: ['SCheckboxGroup', 'SCheckbox', 'SCheckboxCardGroup', 'SCheckboxCard'],
  clipboard: ['SClipboard'],
  code: ['SCode'],
  collapsible: ['SCollapsible', 'SCollapsibleTrigger', 'SCollapsibleContent'],
  colorArea: ['SColorArea'],
  colorField: ['SColorField'],
  colorPicker: ['SColorPicker'],
  colorSlider: ['SColorSlider'],
  colorSwatch: ['SColorSwatch'],
  colorSwatchPicker: ['SColorSwatchPicker'],
  combobox: ['SCombobox'],
  command: ['SCommand'],
  configProvider: ['SConfigProvider'],
  contextMenu: ['SContextMenu', 'SContextMenuCheckbox', 'SContextMenuRadio', 'SContextMenuWrapper'],
  dateField: ['SDateField'],
  datePicker: ['SDatePicker'],
  dateRangeField: ['SDateRangeField'],
  dateRangePicker: ['SDateRangePicker'],
  descriptions: ['SDescriptions', 'SDescriptionsItem'],
  dialog: ['SDialog', 'SDialogProvider'],
  drawer: ['SDrawer'],
  dropdownMenu: ['SDropdownMenu', 'SDropdownMenuCheckbox', 'SDropdownMenuRadio', 'SDropdownMenuWrapper'],
  editable: ['SEditable'],
  ellipsis: ['SEllipsis'],
  empty: ['SEmpty'],
  form: ['SForm', 'SFormFieldBase'],
  hoverCard: ['SHoverCard'],
  icon: ['SIcon'],
  image: ['SImage', 'SImagePreview'],
  input: ['SInput', 'SInputClear'],
  inputNumber: ['SInputNumber'],
  inputOtp: ['SInputOtp'],
  kbd: ['SKbd'],
  label: ['SLabel'],
  layout: ['SLayout', 'SLayoutTrigger'],
  link: ['SLink'],
  list: ['SList', 'SListItem'],
  menu: ['SMenuOptions', 'SMenuCheckboxOptions', 'SMenuRadioOptions'],
  menubar: ['SMenubar'],
  navigationMenu: ['SNavigationMenu'],
  pageTabs: ['SPageTabs'],
  pagination: ['SPagination'],
  palettePicker: ['SPalettePicker'],
  password: ['SPassword'],
  popconfirm: ['SPopconfirm', 'SPopconfirmConfirm', 'SPopconfirmCancel'],
  popover: ['SPopover'],
  progress: ['SProgressProvider', 'SProgress', 'SProgressCircle'],
  radioGroup: ['SRadioGroup', 'SRadioGroupCard'],
  rating: ['SRating'],
  scrollArea: ['SScrollArea'],
  segment: ['SSegment'],
  select: ['SSelect'],
  separator: ['SSeparator'],
  skeleton: ['SSkeleton'],
  slider: ['SSlider'],
  spinner: ['SSpinner'],
  splitter: ['SSplitterGroup', 'SSplitterPanel', 'SSplitterResizeHandle'],
  statistic: ['SStatistic'],
  stepper: ['SStepper'],
  switch: ['SSwitch'],
  table: ['STable', 'STableRow', 'STableCell'],
  tabs: ['STabs'],
  tag: ['STag'],
  tagsInput: ['STagsInput', 'STagsInputItemText', 'STagsInputItemDelete'],
  textarea: ['STextarea', 'STextareaClear'],
  themeCustomizer: ['SThemeCustomizer'],
  themeModeSelect: ['SThemeModeSelect'],
  themeModeSwitch: ['SThemeModeSwitch'],
  timeField: ['STimeField'],
  timeline: ['STimeline', 'STimelineItem'],
  timeRangeField: ['STimeRangeField'],
  toast: ['SToastProvider'],
  toggle: ['SToggle'],
  toggleGroup: ['SToggleGroup', 'SToggleGroupItem'],
  toolbar: [
    'SToolbar',
    'SToolbarButton',
    'SToolbarLink',
    'SToolbarSeparator',
    'SToolbarToggleGroup',
    'SToolbarToggleItem'
  ],
  tooltip: ['STooltip'],
  tree: ['STree', 'STreeVirtualizer', 'STreeItem', 'STreeVirtualizerItem'],
  treeMenu: ['STreeMenu', 'STreeMenuStyledItem'],
  typography: ['STypographyTitle', 'STypographyParagraph', 'STypographyText'],
  virtualizer: ['SVirtualizer', 'SVirtualizerItem'],
  watermark: ['SWatermark']
};
