<script setup lang="ts">
import { h, watchEffect } from 'vue';
import { useOmitProps } from '@soybeanjs/headless/composables';
import { ConfigProvider } from '@soybeanjs/headless/config-provider';
import { isClient, transformPropsToContext } from '@soybeanjs/headless/shared';
import DialogProvider from '../dialog/dialog-provider.vue';
import Icon from '../icon/icon.vue';
import type { IconValue } from '../icon/types';
import ProgressProvider from '../progress/progress-provider.vue';
import ToastProvider from '../toast/toast-provider.vue';
import { provideConfigProviderContext } from './context';
import type { ConfigProviderProps } from './types';

defineOptions({
  name: 'SConfigProvider'
});

const props = withDefaults(defineProps<ConfigProviderProps>(), {
  theme: () => ({}),
  size: 'md',
  iconify: () => ({
    width: '1.25em',
    height: '1.25em'
  })
});

const forwardedProps = useOmitProps(props, [
  'iconRender',
  'theme',
  'size',
  'iconify',
  'progress',
  'toast',
  'customToast'
]);

const iconRender = props.iconRender ?? ((icon: IconValue) => h(Icon, { icon, ssr: import.meta.env.SSR }));

provideConfigProviderContext({
  ...transformPropsToContext(props),
  iconRender
});

// Apply theme attributes to <html> for CSS [data-*] selector matching.
// All color/radius/size variants are pre-generated by presetShadcn at build time.
watchEffect(
  () => {
    if (!isClient) return;

    const doc = document.documentElement;
    const theme = props.theme ?? {};

    doc.dataset.size = props.size ?? 'md';

    if (theme.base) doc.dataset.base = theme.base;
    if (theme.primary) doc.dataset.primary = theme.primary;
    if (theme.feedback) doc.dataset.feedback = theme.feedback;
    if (theme.radius) doc.dataset.radius = theme.radius;
    if (theme.menuColor) doc.dataset.menuColor = theme.menuColor;
    if (theme.menuAccent) doc.dataset.menuAccent = theme.menuAccent;
  },
  { flush: 'post' }
);
</script>

<template>
  <ConfigProvider v-bind="forwardedProps" :icon-render="iconRender">
    <slot />
    <ToastProvider v-if="!props.customToast" v-bind="props.toast" />
    <DialogProvider />
    <ProgressProvider v-bind="props.progress" />
  </ConfigProvider>
</template>
