/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('@soybeanjs/ui')['SButton']
    SMenuOption: typeof import('@soybeanjs/ui')['SMenuOption']
    ThemeConfigurator: typeof import('./../components/theme-configurator.vue')['default']
    ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SButton: typeof import('@soybeanjs/ui')['SButton']
  const SMenuOption: typeof import('@soybeanjs/ui')['SMenuOption']
  const ThemeConfigurator: typeof import('./../components/theme-configurator.vue')['default']
  const ThemeSchemaToggler: typeof import('./../components/theme-schema-toggler.vue')['default']
}